---
- name: Install prerequisites
  apt:
    name: ["gnupg", "curl"]
    state: present
    update_cache: yes

- name: Add MongoDB 8.0 repository
  block:
    - name: Ensure keyrings directory
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
    
    - name: Import MongoDB GPG key
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg --batch -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
      args:
        creates: /usr/share/keyrings/mongodb-server-8.0.gpg
    
    - name: Add repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse"
        filename: mongodb-org-8.0.list
        state: present

- name: Install MongoDB 8.0.5
  apt:
    name:
      - mongodb-org=8.0.5
      - mongodb-org-database=8.0.5
      - mongodb-org-server=8.0.5
      - mongodb-org-shell=8.0.5
    state: present
    force: yes
    update_cache: yes
  notify: 
    - daemon-reload
    - restart mongodb

- name: Configure MongoDB directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'
  loop:
    - /var/lib/mongodb
    - /var/log/mongodb

- name: Configure MongoDB
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongodb
    group: mongodb
    mode: '0644'
  notify:
    - daemon-reload
    - restart mongodb

- name: Ensure MongoDB is running
  service:
    name: mongod
    state: started
    enabled: yes